spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.92.35.7/yunpark?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: park
    password: park123